### ISSUE TITLE
Dropbox app is frozen and pending review

### ISSUE THREAD

**Issue by aoberoi** [karaggeorge/kap-dropbox#4] opened 2020-10-28 12:07 UTC
The maintainers might already be aware of this, but it would be useful for users to know about the issue. I suggest putting a notice in the README that the plugin is currently not working because of this issue.

<img width="604" alt="Screen Shot 2020-10-28 at 5 04 18 AM" src="https://user-images.githubusercontent.com/494795/97433721-302b9880-18db-11eb-9bd3-4f0df174ab07.png">

Also, is there anything users can do to help get the app out of review? Is there any info you can share about how or when this might be resolved?

**Comment by karaggeorge** [comment] 2020-10-28 16:24
Hey @aoberoi , the way Dropbox handles app integrations is that they are in sandbox mode until they reach a certain number of authenticated users. At that point, Dropbox freezes the integration and you can apply for review to turn to production mode, which then allows you unlimited users.

When I built this originally, I went through the review process, but I got denied because Auth flow was in a webview instead of a browser. Now that Kap supports deep-linking, I've recreated the plugin. Thank you for letting me know the limit has been reached. I have submitted this new integration for review. They don't provide a timeline as to how long it'll take, but last time I heard back within 2 weeks.

I'll update here when I have more info

**Comment by NoLooseEnds** [comment] 2020-11-20 14:11
Same issue today.

A feature request (that I'm not totally sure if it's there or not) is to auto copy the dropbox share URL after upload, just like Dropbox do when you integrate it with the macOS screenshot.

**Comment by karaggeorge** [comment] 2020-11-20 17:01
Hey, I actually heard back from them and they denied my request because they couldn't validate it. I'm working with them trying to get it sorted out.

As for the link thing, that's already implemented, so when this whole permission/user-limit thing is fixed, when you use the plugin, you see a notification and the link is copied to your clipboard

**Comment by NoLooseEnds** [comment] 2020-11-20 17:59
Great! 

I have a few mixed experiences with Dropbox support – both in their technical know how in the first line support – and their response time in the second/third line. I'm still waiting for them on an issue from September (Business version) – so it could be awhile.

**Comment by karaggeorge** [comment] 2020-11-20 19:54
Well, I hope it gets resolved soon 😄 I'll update here whenever I know more. I can say I'm not a big fan of this whole freezing when you reach x amount of users until your app gets approved. I feel like they could let you submit for prod when you reach a user goal, keeping the sandbox version going until the result is reached. Pretty much they way they have it now, without the freezing for new users

**Comment by karaggeorge** [comment] 2020-12-13 21:14
This got approved. Can anyone confirm?

**Comment by NoLooseEnds** [comment] 2020-12-13 21:21
Confirmed. Approved and worked. 👍 🥇 

I have one feature request btw:
Is it possible to change the last part of the dropbox share URL to: `?raw=1`, instead of `?dl=0`? That way you get the "clean" file without the dropbox interface?

(or maybe make a toggle in the prefs)

**Comment by karaggeorge** [comment] 2020-12-26 03:28
I get the link from the dropbox api response. I could parse it and swap the two. I'll close this one, but feel free to open a new issue with the above. I'll try to work on it when I get a chance. PRs are of course always welcome.

**Closed as completed by karaggeorge** 2020-12-26 03:28 UTC
